# This file is automatically merged with docker-compose.yml by Docker.
# It contains local development specific configurations (ports, volumes, etc.)

services:
  dashboard:
    volumes:
      - ./dashboard/server:/app/server
      - ./dashboard/entrypoint.sh:/app/entrypoint.sh

  rpa:
    volumes:
      - ./rpa:/app

  vpn-auth:
    volumes:
      - ./rpa:/app

  archiver:
    volumes:
      - ./rpa:/app

  fasih-db:
    ports:
      - "5432:5432"

  master:
    ports:
      - "9333:9333"

  s3:
    ports:
      - "8333:8333"

